config/routes.rb
Rails.application.routes.draw do
  resources :plants
root 'welcome#index'

end

app/models/plant.rb
class Plant < ActiveRecord::Base
    #belongs_to :cathegory, dependent: :destroy
    mount_uploader :foto, FotoUploader
    validates :name, presence: true
    
    # It returns the articles whose titles contain one or more words that form the query
  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("name like ?", "%#{query}%") 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
    def index
    @plants = Plant.all
        
        if params[:search]
          @plants = Plant.search(params[:search])
        end
    end
    

  def show
    @plant = Plant.find(params[:id])
    
  end
    
    def new
        @plant = Plant.new
        #plant.foto = params[:file]
        
    end
    
    def edit
        @plant = Plant.find(params[:id])
    end
      
    def create
        @plant = Plant.new(plant_params)
        if @plant.save
        redirect_to @plant
        end
    end
   
    def update
        @plant = Plant.find(params[:id])
        if @plant.update(plant_params)
        redirect_to @plant
        else
        render 'edit'
        end
    end
    def destroy
     @plant = Plant.find(params[:id])
     @plant.destroy
     redirect_to plants_path
    end


 private
  def plant_params
    params.require(:plant).permit(:name, :latin, :family, :category, :condition, :foto)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Encyklopedia Roślin
    by Hanna Buczyńska</a>
  </small>
  
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-static-top">   
      <nav>
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
           
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home",   root_path %></li>
            <li><a href="#">Informacje</a></li>
            <li><a href="#">Galeria</a></li>
         
         
        <li><%= link_to "Rośliny",   plants_path %></li>
        <li><%= link_to "Kategorie",  " #" %></li>
        <li><%= link_to "Help",   '#' %></li>
        <li><%= link_to "Log in", '#' %></li>
        <li>
        </ul>
            
          <ul class="nav navbar-nav navbar-right">  
          <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
           
            <%= form_tag(plants_path, :method => "get", class: "navbar-form", id: "search-form") do %>
            <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Szukaj" %>
        </div>
        <button type="submit" class="btn btn-default">Szukaj</button>
      </form>
      <% end %>
        </li>
      </ul>
    </nav>
<%= link_to image_tag("meczennica_f3.jpg", id: "banner"), '#' %>
  <div class="container">
    
    <%= link_to "Encyklopedia Roślin", '#', id: "logo" %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Encyklopedia Roślin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <body>
        <%= render 'layouts/header' %>
        

      <div class="container">
        
    
<%= yield %>
<p></p>
      <%= render 'layouts/footer' %>

</body>
</html>

app/views/plants/edit.html.erb
<h1>Edytowanie rośiny</h1>
 <%= form_for :plant, url: plant_path(@plant), method: :patch do |f| %>
   
   <p>
    <%= f.label "Nazwa" %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label "Nazwa łacińska" %><br>
    <%= f.text_field :latin %>
  </p>
  <p>
    <%= f.label "Rodzina" %><br>
    <%= f.text_area :family %>
  </p>
   <p>
    <%= f.label "Uprawa" %><br>
    <%= f.text_area :condition %>
  </p>
  <p>
      <%= f.label "Dodaj zdjęcie" %><br>
      <%= f.file_field :foto %>
  </p>
   <p>
    <%= f.submit %>
  </p>
   <% end %>
 <%= link_to 'Powrót', plants_path %>
 

app/views/plants/index.html.erb
<div class="center jumbotron">
<% if @plants.size == 0 %>
    <h2> Brak wpisów! </h2>
    <% end %>
<%= link_to 'Dodaj nową roślinę', new_plant_path %>
<table>
  <tr>
    <th>Nazwa</th>
    <th colspan="2"></th>
  </tr>
   <% @plants.each do |plant| %>
    <tr>
      <td><%= plant.name %></td>
      <td><%= link_to 'Pokaż', plant_path(plant) %></td>
      <td><%= link_to 'Edytuj', edit_plant_path(plant) %></td>
      <td><%= link_to 'Usuń', plant_path(plant),
              method: :delete,
              data: { confirm: 'Czy napewno usunąć?' } %></td>
  
    </tr>
    
  <% end %>
   
</table>
</div>

app/views/plants/new.html.erb
<h1>Nowa roślina</h1>
 
 <%= form_for :plant, url: plants_path do |f| %>
  <p>
    <%= f.label "Nazwa" %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label "Nazwa łacińska" %><br>
    <%= f.text_field :latin %>
  </p>
  <p>
    <%= f.label "Rodzina" %><br>
    <%= f.text_area :family %>
  </p>
   <p>
    <%= f.label "Uprawa" %><br>
    <%= f.text_area :condition %>
  </p>
  <p>
      <%= f.label "Dodaj zdjęcie" %><br>
      <%= f.file_field :foto %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Powrót', plants_path %>

app/views/plants/show.html.erb
<div class="center jumbotron">
<h1><%= @plant.name %></h1>
<h3><%= @plant.latin %></h3>
  
 <p>
  <strong>Rodzina:</strong>
  <%= @plant.family %>
</p>

<p>
    <%= image_tag @plant.foto, class: "zdjecie" %>
</p>

<p>
  <strong>Uprawa:</strong>
  <%= @plant.condition %>
</p>


<%= link_to 'Powrót', plants_path %>
</div>

app/views/welcome/index.html.erb
<div class="center jumbotron">

    <h1>Encyklopedia Roślin</h1>
    <p>Encyklopedia roślin to strona o uprawie roślin egzotycznych. Wpisy będą systematycznie uzupełniane.</p>
        <p>Uwagi i wskazówki mile widziane.</p>
</div>